# Generated by Django 4.1.2 on 2022-11-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele', models.CharField(max_length=20, verbose_name='Телефон')),
                ('gmail', models.CharField(max_length=50, verbose_name='Почта')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('Adres', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Данные о заказе',
                'verbose_name_plural': 'Данные о заказах',
            },
        ),
    ]
